name: Sync with Upstream

on:
  schedule:
    # Run every Sunday at midnight UTC
    - cron: "0 0 * * 0"

  workflow_dispatch: # Allows manual trigger of the workflow
    inputs:
      reason:
        description: "Reason for manual sync"
        required: false

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your fork repository
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for tags and branches

      # Step 2: Configure Git Identity
      - name: Configure Git Identity
        run: |
          git config --global user.email "admin@sumwall.com"
          git config --global user.name "Admin"

      # Step 3: Get the Upstream Repository URL
      - name: Get Upstream URL
        id: get-upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch upstream URL using GitHub API
          repo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository_owner }}/$repo)
          upstream_url=$(echo $response | jq -r '.parent.clone_url')
          echo "Upstream URL: $upstream_url"
          echo "::set-output name=url::$upstream_url"

      # Step 4: Add upstream remote dynamically
      - name: Add Upstream Remote
        if: steps.get-upstream.outputs.url != 'null'
        run: git remote add upstream ${{ steps.get-upstream.outputs.url }}

      # Step 5: Fetch tags and branches from upstream
      - name: Fetch Upstream Tags and Branches
        run: git fetch upstream --tags

      # Step 6: Merge upstream/master into fork's master branch
      - name: Merge Upstream into Fork
        run: |
          git checkout master
          git merge upstream/master || echo "No new changes to merge."

      # Step 7: Push changes to your fork
      - name: Push Changes to Fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master
          git push origin --tags
